version: "3.9"

services:
  database:
    image: postgres
    container_name: dbcar
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=rentalcar
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  
  
  app:
    build: .
    container_name: rentalcar
    ports:
      - 3333:3333
      - 9229:9229 #debug
    volumes:
      - .:/usr/app
    # network_mode: host
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local