version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ignite_rentalcar
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  
  
  app:
    build: .
    container_name: ignite_rentalcar
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local